In [1]:
import pandas as pd
import os
os.getcwd()

'c:\\repo\\DeVal2\\services\\server\\tests'

In [2]:
df = pd.read_csv('../project/data/ORE/Input/Static/market_20160205.csv', header=None)
df.columns = ['Date', 'Name', 'Value']

In [23]:
cpty_a_df = df[df['Name'].str.contains('CPTY_A')]
cpty_b_df = cpty_a_df.copy()
cpty_b_df['Name'] = cpty_b_df['Name'].str.replace('CPTY_A', 'CPTY_B')
cpty_b_df

            Date                                   Name  Value
3393  05/02/2016       RECOVERY_RATE/RATE/CPTY_B/SR/USD   0.40
3394  05/02/2016      HAZARD_RATE/RATE/CPTY_B/SR/USD/0Y   0.01
3395  05/02/2016      HAZARD_RATE/RATE/CPTY_B/SR/USD/1Y   0.01
3396  05/02/2016      HAZARD_RATE/RATE/CPTY_B/SR/USD/2Y   0.01
3397  05/02/2016      HAZARD_RATE/RATE/CPTY_B/SR/USD/3Y   0.01
3398  05/02/2016      HAZARD_RATE/RATE/CPTY_B/SR/USD/4Y   0.01
3399  05/02/2016      HAZARD_RATE/RATE/CPTY_B/SR/USD/5Y   0.01
3400  05/02/2016      HAZARD_RATE/RATE/CPTY_B/SR/USD/7Y   0.01
3401  05/02/2016     HAZARD_RATE/RATE/CPTY_B/SR/USD/10Y   0.01
3402  05/02/2016     HAZARD_RATE/RATE/CPTY_B/SR/USD/15Y   0.01
3403  05/02/2016     HAZARD_RATE/RATE/CPTY_B/SR/USD/20Y   0.01
3404  05/02/2016     HAZARD_RATE/RATE/CPTY_B/SR/USD/30Y   0.01
7985  05/02/2016  INDEX_CDS_OPTION/RATE_LNVOL/CPTY_B/1M   0.85
7986  05/02/2016  INDEX_CDS_OPTION/RATE_LNVOL/CPTY_B/3M   0.85
7987  05/02/2016  INDEX_CDS_OPTION/RATE_LNVOL/CPTY_B/6M   0.85
7988  05/02/2016  INDEX_CDS_OPTION/RATE_LNVOL/CPTY_B/1Y   0.85
7989  05/02/2016  INDEX_CDS_OPTION/RATE_LNVOL/CPTY_B/2Y   0.80
7990  05/02/2016  INDEX_CDS_OPTION/RATE_LNVOL/CPTY_B/3Y   0.75
7991  05/02/2016  INDEX_CDS_OPTION/RATE_LNVOL/CPTY_B/4Y   0.70
7992  05/02/2016  INDEX_CDS_OPTION/RATE_LNVOL/CPTY_B/5Y   0.64
8021  05/02/2016       RECOVERY_RATE/RATE/CPTY_B/SR/USD   0.40
8022  05/02/2016      HAZARD_RATE/RATE/CPTY_B/SR/USD/0Y   0.01
8023  05/02/2016      HAZARD_RATE/RATE/CPTY_B/SR/USD/1Y   0.01
8024  05/02/2016      HAZARD_RATE/RATE/CPTY_B/SR/USD/2Y   0.01
8025  05/02/2016      HAZARD_RATE/RATE/CPTY_B/SR/USD/3Y   0.01
8026  05/02/2016      HAZARD_RATE/RATE/CPTY_B/SR/USD/4Y   0.01
8027  05/02/2016      HAZARD_RATE/RATE/CPTY_B/SR/USD/5Y   0.01
8028  05/02/2016      HAZARD_RATE/RATE/CPTY_B/SR/USD/7Y   0.01
8029  05/02/2016     HAZARD_RATE/RATE/CPTY_B/SR/USD/10Y   0.01
8030  05/02/2016     HAZARD_RATE/RATE/CPTY_B/SR/USD/15Y   0.01
8031  05/02/2016     HAZARD_RATE/RATE/CPTY_B/SR/USD/20Y   0.01
8032  05/02/2016     HAZARD_RATE/RATE/CPTY_B/SR/USD/30Y   0.01
8033  05/02/2016       RECOVERY_RATE/RATE/CPTY_B/SR/EUR   0.40
8034  05/02/2016      HAZARD_RATE/RATE/CPTY_B/SR/EUR/0Y   0.01
8035  05/02/2016      HAZARD_RATE/RATE/CPTY_B/SR/EUR/1Y   0.01
8036  05/02/2016      HAZARD_RATE/RATE/CPTY_B/SR/EUR/2Y   0.01
8037  05/02/2016      HAZARD_RATE/RATE/CPTY_B/SR/EUR/3Y   0.01
8038  05/02/2016      HAZARD_RATE/RATE/CPTY_B/SR/EUR/4Y   0.01
8039  05/02/2016      HAZARD_RATE/RATE/CPTY_B/SR/EUR/5Y   0.01
8040  05/02/2016      HAZARD_RATE/RATE/CPTY_B/SR/EUR/7Y   0.01
8041  05/02/2016     HAZARD_RATE/RATE/CPTY_B/SR/EUR/10Y   0.01
8042  05/02/2016     HAZARD_RATE/RATE/CPTY_B/SR/EUR/15Y   0.01
8043  05/02/2016     HAZARD_RATE/RATE/CPTY_B/SR/EUR/20Y   0.01
8044  05/02/2016     HAZARD_RATE/RATE/CPTY_B/SR/EUR/30Y   0.01

In [24]:
df = pd.concat([df, cpty_b_df], ignore_index=True, axis=0)
df.to_csv('../project/data/ORE/Input/Static/market_20160205_with_cpty.csv', index=False, header=False)

In [6]:
df['Category'] = df.Name.str.split('/').str[0]

In [ ]:
categories = [
    'ZERO',
    'FX',
    'FXFWD',
    'MM',
    'FRA',
    'IR_SWAP',
    'BASIS_SWAP',
    'CC_BASIS_SWAP',
    'FX_OPTION',
    'CAPFLOOR',
    'SWAPTION'
]

In [26]:
df[df.Category == 'DISCOUNT']

Empty DataFrame
Columns: [Date, Name, Value, Category]
Index: []